name: Media Service Workflow - build

on:
  push:
    branches: [ "release/R58" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: yarn --frozen-lockfile
      - run: npm run build:media-workflows:prod
      - name: Drop workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: media-service-workflow
          path: "*.tgz"
      